// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAQuN0eqLEhPzUA91Qcqp-RK9pks5eoF0g",
      authDomain: "protfolio-7e387.firebaseapp.com",
      projectId: "protfolio-7e387",
      storageBucket: "protfolio-7e387.appspot.com",
      messagingSenderId: "1003182723868",
      appId: "1:1003182723868:web:2b92bfc60bdf56e81d20d9");

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyANmtkYrCx07M1Ltv5D4J3EchXgTChYFac',
  //   appId: '1:704702903857:android:4555b7faa6f56b6aa34710',
  //   messagingSenderId: '704702903857',
  //   projectId: 'portfolio-1bcf5',
  //   storageBucket: 'portfolio-1bcf5.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBXrjJ_7bCMGVJMBj7tQ3-gy2vN28JcjXs',
  //   appId: '1:704702903857:ios:4e626e44215b70cea34710',
  //   messagingSenderId: '704702903857',
  //   projectId: 'portfolio-1bcf5',
  //   storageBucket: 'portfolio-1bcf5.appspot.com',
  //   iosBundleId: 'com.example.portfolio',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBXrjJ_7bCMGVJMBj7tQ3-gy2vN28JcjXs',
  //   appId: '1:704702903857:ios:67993b6de192e940a34710',
  //   messagingSenderId: '704702903857',
  //   projectId: 'portfolio-1bcf5',
  //   storageBucket: 'portfolio-1bcf5.appspot.com',
  //   iosBundleId: 'com.example.portfolio.RunnerTests',
  // );
}
